# PostgreSQL
db:
  # 数据库连接地址
  host:        "127.0.0.1"
  # 数据库连接端口（PostgreSQL 默认端口是 5432）
  port:        5432
  # 数据库名称
  name:        "PokeForum"
  # 数据库用户名
  username:    "PokeForum"
  # 数据库密码
  password:    "<PASSWORD>"
  # 数据库连接配置（PostgreSQL DSN）
  config: 'sslmode=disable'

# Redis
cache:
  # 缓存连接地址
  host: "127.0.0.1"
  # 缓存连接端口（Redis 默认端口是 6379）
  port: 6379
  # 缓存密码
  password: ""
  # 缓存库
  db: 0